version: '2'

services:
 
  elastic:
    image: elasticsearch:5.4.0
    container_name: elastic
    command: "-Ecluster.name=StarGraphV2Cluster -Ebootstrap.memory_lock=true -Ediscovery.zen.minimum_master_nodes=1 -Ecluster.routing.allocation.disk.threshold_enabled=false -Etransport.host=0.0.0.0 -Ediscovery.type=single-node"
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 3g
    cap_add:
      - IPC_LOCK
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
